### ISSUE TITLE
프로젝트 시작을 위해 필요한 API 명세 설계에 대한 방안을 도출한다. (~07.04 - 23:59)  

### ISSUE THREAD

**Issue by 2SOOY** [woowacourse-teams/2021-gpu-is-mine#1]

**Comment by sjpark-dev** [comment]
제안
- 07.05월 API 명세를 설계
- 프론트는 회의(약 2시간)를 통해 프런트의 API 명세서를 간략히 작성
- 백도 마찬가지로 백의 API 명세서를 간략히 작성
- 이후 전체 회의(약 2시간)를 통해 각가의 API 명세를 합쳐서 초안을 작성
- API 명세에는 각 기능의 HTTP Request와 HTTP Response에 필요한 정보 포함

**Comment by ecsimsw** [comment]
제안 

- 07.05 프론트, 백 파트별 회의 필요
- 프론트 : 필요한 화면 목록과, 보
- 07.06 화요일에 API 명세 설계
- 전체적인 틀, 기능적인 부분에서, 팀원별 생각을 맞춰야하는 내용이 분명히 있다고 생각한다. (예를 들면 소켓의 사용)
-

**Comment by knae11** [comment]
# 월요일

- 로그인이 필요없다고 판단되는 관리자 영역에 한해서 명세 도출(혹여 로그인이 필요하다고 하더라도 일단 없이 진행)
- GPU 등록, 현황확인, 삭제 등의 기능 구현하기 위한 명세
- 진행방식
    - 백에서 먼저 대략적인 데이터 협의(~화), 프론트는 시안 협의(~화) => 각각 필요한 데이터 도출
    - 프론트&백 명세 협의(화)
    - 기능 간단하게 구현(~목), 금요일에 기능 연동해보기

**Comment by wannte** [comment]
## 전체적인 구현 플로우에 대한 생각
전체 모든 기능에 대한 구체적인 API 명세를 지금 이 시점에 다 정하고 구현을 해야 하는지에 의구심이 듦.

특히 GM이 어떤 역할을 하는지 너무나도 추상적으로 주어져 있는데, 이 부분은 사람마다 의견이 다르고, 우리끼리 의견이 모인다고 해도, 우리가 직접 다 구현하는 부분이 아니기 때문에 기업측과도 의견 수렴이 필요함.

프로젝트를 크게 12, 단계로 나누어 진행했으면 좋겠고, 지금은 1단계만 집중하여 진행했으면 좋겠음
1. Queue에 값을 넣기 전까지의 구현
 - GPU 등록/삭제/조회
 - User 관련 로직
 - Job 예약하고 Queue 에 넣는 로직
2. 그 이후의 구현

1단계를 구현하다 보면, 조금 더 2단계의 구현이 구체화가 될 수 있을 거라 생각합니다!

## 다음주 월요일 회의에 대한 생각
1. 위에서 정의한 1단계의 기능들과 api들을 선정한다.
2. 도메인(정의한 기능들의 특징 : 사용자 관련, GPU관련)마다 2,3명씩 팀을 나누어 API의 초안 명세를 작성한다.
3. 전체 회의에서  API에 대한 설명을 진행한다. 이때 자유롭게 다른 팀들이 추가할 기능들을 말해주는 시간을 가진다.

온라인으로 진행한다는 전제하에 작성하였습니다.
7명이 모두 온라인으로 진행했을때에는 어쩔 수 없이 보이스가 꼬이기 때문에, 2~3명씩 팀을 나누면 좋을 것 같습니다.
또한, 1,2단계를 나누어 1단계에만 집중한다면 월요일 안에 충분히 좋은 결과를 낼 수 있지 않을까 생각합니다.

**Comment by MyaGya** [comment]
# 월요일 시나리오

## 공통

- 프로젝트 플로우 설계
- 프로젝트 화면 설계
- 대략적인 API 설계

## 각 팀

- 사용 기술 선정

## 기타

- 완벽한 뼈대를 만드는 게 아니라 임시적인 뼈대를 만드는 걸 목적
- 나중에 도입해도 되는 기술의 분리, 필요성 → 기술 도입 이 가능한 기술과 아닌 기술 구별 필요 (CI / CD)

**Comment by bigsaigon333** [comment]
기존의 우테코 미션들과 다르게 요구사항이 구체적으로 주어지지 않았으며, 언제든지 변경・추가될 가능성이 높은 상황입니다.

따라서 전체 API 명세 또는 전체 DB 설계를 다 하고 구현을 진행하는 것은, 
금요일 오전의 포비 수업에서 보여준 소식지 100개 접기 동영상에서 100개의 종이를 다 접은 다음에 100개의 종이를 편지봉투에 넣는 것과  유사하지 않나.. 라는 생각이 듭니다.

애자일하게 매우 작은 부분부터 하나씩 구현해 보고 싶습니다.

------이하 나의 의견-------

API 설계, DB 설계, 기획, UI 설계, 와이어프레임 작성, 코드 작성 등을 언제까지 끝낸다고 정하는 거 자체가 의미가 없는 것 같습니다. 
다 동시에 진행합니다. 따라서 언제든지 변경될 수 있다는 점을 항상 인지하고 변화에 유연하게 대응할 수 있게 확장성을 염두에 두고 설계하고 구현합니다. 

### 7/5 월요일

1. FE, BE 기술스택 선정 및 환경설정 -> Local에서 FE, BE 통신 (2시간)
- Local에서 FE, BE 통신을 목표로 가장 최소로 필요한 것들만 선정해서 설치, 환경설정 완료.
- Local에서 FE, BE 통신과 상관없으나 논의가 많이 필요한 기술스택은 추후에 지속적으로 논의해서 선정. 

2. 먼저 구현할 가장 작은 단위의 기능 선택 (15~30분)
- 가장 설계할 것이 작고 다른 것에 대한 의존성이 낮을 것으로 예상되는 최소 기능 선정(예시: 회원가입 또는 GPU 등록)

3. 선택한 기능에 대한 API, DB, UI 설계(1시간 내외)
- API, DB, UI 설계
- 가능하면 다 같이 하면 좋을거 같은데, 기술적으로 힘들거나 따로 하는게 나을거 같다는 의견 있으면 따로 해도 좋음

4. 3.을 구현하기 위하여 필요한 기술스택 선정 및 코드 작성(1시간 내외)
- 무적권 코드를 작성해본다... 무 적 권...

5.
