### ISSUE TITLE
UI 고도화

### ISSUE THREAD

**Issue by bigsaigon333** [woowacourse-teams/2021-gpu-is-mine#112]
## 0. 공통
- [x] 비동기 호출 status === "loading" 일 때 로딩중을 나타내는 UI 적용
  - [x] 스피너 absolute 등으로 스크린 내에 항상 표시되게 하게
- [x] https 대응 +  baeURL 상수화
- [x] 불필요한 console.log 지우기
- [x] Portal cleanup function 확인 -> 최상단 div는 살아있음

## 1. 조회페이지
- [x] 등록된 GpuServer가 없을 때 보여줄 UI
- [x] Sub-header 가 url 에 따라 변경 
- [x] Lab 이름 하나로 고정(하드코딩)
- [ ] 랩탑뷰에서 InfoItem column간 간격 너무 큼
- [x] 삭제 버튼 클릭시 Custom Confirm 컴포넌트로 유저에게 다시 한 번 확인
  - [ ] Dimmed 색상 확인(현재 누리끼리하게 보임)
- [x] 삭제 성공 또는 실패시 Custom Alert 컴포넌트로 유저에게 알려주기
  - [ ] Dimmed 색상 확인(현재 누리끼리하게 보임)

## 2. 등록페이지
- [x] Form Validation
  - [x] 글자수 제한
  - [x] 숫자만 입력하게 하기
- [x] box-shadow 살짝 줘서 배경에서 살짝 띄어져 있는 느낌 주기
- [x] 제출 완료시 Custom Alert 띄우기
- [x] 제출 진행시에도 또 제출 되지 않게 하기

## 3. Layout
- [x] Footer background-color를 Content background-color 와 일치시킨다

###  Custom Alert 등
- [ ] Custom Alert 등open, close 시 애니메이션 추가
### 등록페이지
- [ ] Validation 타이밍
  - [ ] 원칙적으로 Blur 타이밍에 validation 
  - [ ] invalid한 Input은 Change 타이밍에 validation 
  - [ ] 다른 Input이 모두 valid할 때 마지막 Input은 change 타이밍에 validation

**Comment by 2SOOY** [comment]
테스트 !

**Comment by bigsaigon333** [comment]
# 추후 대응
## 1. 조회페이지
- [ ] 랩탑뷰에서 InfoItem column간 간격 너무 큼

##  Custom Alert 등
- [ ] Custom Alert 등open, close 시 애니메이션 추가

## 등록페이지
- [ ] Validation 타이밍
  - [ ] 원칙적으로 Blur 타이밍에 validation 
  - [ ] invalid한 Input은 Change 타이밍에 validation 
  - [ ] 다른 Input이 모두 valid할 때 마지막 Input은 change 타이밍에 validation
