### ISSUE TITLE
Job의 api url을 논의하여 결정한다.

### ISSUE THREAD

**Issue by wannte** [woowacourse-teams/2021-gpu-is-mine#128]
# 이슈 설명

job api 형식을 결정한다.

**Comment by wannte** [comment]
개인적인 생각을 남겨봐요. 요런 방식도 있구나 정도로 생각했으면 해요!~

저는 job - gpuServer - member 가  api 구조상은 같은 계층에 있어야 한다고 생각해요.
특정 lab 안에 job, gpuServer, member 가 존재하는 방식으로요.

Job이 gpuServer 내부에 존재한다기 보다는, Job의 실행위치가 gpuServer다 라는 관점이에요.
마찬가지로 Job이 어떤 member의 소유라는 개념보다는 Job을 요청한 사람이 Member 이다.

이러한 관점으로 제가 생가하는 api의 구조는 다음과 같아요

1. jobs 조회
```java
@GetMapping("/api/labs/{labId}/jobs")
public List<JobResponse> findJobs(
            @PathVariable Long labId,
            @RequestParam(value = "gpuServer", required = false) Long gpuServerId,
            @RequestParam(value = "member", required = false) Long memberId)
}
```
> 우선은 token을 고려하지 않았습니다.

> Member 가 특정 GpuServer에 예약한 JobList를 보여줄수도 있게 되네요.

2. job 조회
Get /api/labs/{labId}/jobs/{jobId}

3. job 생성
POST  /api/labs/{labId}/jobs

4. job 수정
PUT /api/labs/{labId}/jobs/{jobId}

5. job 삭제
DELETE  /api/labs/{labId}/jobs/{jobId}

**Comment by ecsimsw** [comment]
처리된 이슈라고 생각합니다!
