### ISSUE TITLE
진행중인 api를 정리한다.

### ISSUE THREAD

**Issue by knae11** [woowacourse-teams/2021-gpu-is-mine#147]
# 이슈 설명

- 엑셀로 진행중인 api를 정리한다.

**Comment by knae11** [comment]
api 문서 링크

https://docs.google.com/spreadsheets/d/12JlH36Oltc_EOo3woEob-Pz6llY2SkQ9vsrL1TsdMPg/edit?usp=sharing

**Comment by bigsaigon333** [comment]
by @wannte 

api 회의 결과 공유하겠습니다. 1시간 정도 소요되서 나름 적은 시간에 회의 완료할 수 있었습니다.
회의에 참여해준 @배럴 @마갸 참관해준 @동동 (0.5 참여) @콜린 수고하셨습니다.
정리된 사항 몇가지 공유해드리겠습니다.
## members를 제외한 모든 api에는 labs/{labId} 가 PathVariable로 들어가기로 결정했습니다.
모든 경우를 리소스/리소스/리소스 안에 넣는 방식으로 PathVariable 방식을 사용하게 되었을 때, 모든 경우에서 메소드가 PathVariable을 다 사용하지는 않게 됩니다.(많은 경우, 사용되지 않는 경우가 발생합니다.) 이런 상황에서 잘못된 요청이 들어와도 사용되지 않는 PathVariable을 위한 검증을 별도로 진행해야 합니다.
하지만, 공통적으로 이야기 된 부분은, 회원가입을 제외한 우리의 모든 서비스는 Lab의 소속이 인증이 되었을 떄, 진행해야 한다는 것이였습니다. 이를 해결하기 위해서, labs/{labId} 의 정보와 token으로 부터 얻은 Member의 labId를 비교하는 인터셉터를 만들어 진행하게 되면, 로직에만 집중된 작업을 할 수 있을 것이라 생각하였고 위의 결정을 내렸습니다.
## query param의 사용
gpuServer에 따른 job 조회의 경우 query_param으로 조회를 진행하게 되고, 가능하면 status에 따른 조회 기능도 query_param으로구현되면 좋겠다는 의견이 나왔습니다.
## 개별 Member jobs 조회
/api/labs/{labId}/jobs/me
의 방식을 선택하였습니다.
조회 후 각 조회를 /api/labs/{labId}/jobs/{jobId} 의 방식을 사용하고 싶었고, members/me에서 차용했습니다.
결정된 api는 아래 문서에서 확인할 수 있습니다. 문서화 작업을 해준 @배럴 감사합니다!

**Comment by bigsaigon333** [comment]
**swagger**

http://3.35.169.99:8080/swagger-ui.html
