### ISSUE TITLE
URL Path의 통일, PathVariable 자원 검증을 대화한다.

### ISSUE THREAD

**Issue by ecsimsw** [woowacourse-teams/2021-gpu-is-mine#149]
백엔드 크루끼리 path에 대한 통일을 못 맞췄습니다.
단순 스타일 문제가 아닌, 로직에도 의미를 갖을 것 같아 이슈로 남겼습니다.

서버의 요청 path에 대한 백엔드 크루의 틀을 만들고, 자원에 대한 검증을 이야기 할 필요가 있을 것 같습니다.

개인적인 생각으로는 관심이 있는 크루만 참여하여 따르겠다는 팀원의 비용을 아끼고,
참여자는 본인의 생각하는 명확한 규칙이나, 아예 모든 Url을 다 짜오는 등, 본인이 지향하는 바를 명확히하여 참여하면 어떨까 생각합니다. 

회의 내용이라던가, 참여자 또는 규칙에 대한 의견을 댓글로 남겨주시길 부탁드리겠습니다.

======= 예시 코드 ========

이를 테면 아래 핸들러들에선, labId가 사용되지 않습니다. 작업하려는 gpuServer가 해당 lab에 속하는지, 존재하는 labId인지, 사용자가 해당 lab에 속해있는지 전혀 판별하지 않습니다. 

즉 유저가 serverId=1에 권한만 있다면 '/api/labs/324278641286/gpus/1' 도 문제없이 요청을 수행하게 되는 것입니다.

<img width="910" alt="image" src="https://user-images.githubusercontent.com/46060746/126732502-9e3165bc-5cf6-4bb4-a9c6-987232ea0a03.png">

**Comment by wannte** [comment]
api 회의 결과 공유하겠습니다. 1시간 정도 소요되서 나름 적은 시간에 회의 완료할 수 있었습니다.
회의에 참여해준 @배럴 @마갸 참관해준 @동동 (0.5 참여) @콜린 수고하셨습니다.
정리된 사항 몇가지 공유해드리겠습니다.

## members를 제외한 모든 api에는 labs/{labId} 가 PathVariable로 들어가기로 결정했습니다.
모든 경우를 리소스/리소스/리소스 안에 넣는 방식으로 PathVariable 방식을 사용하게 되었을 때, 모든 경우에서 메소드가 PathVariable을 다 사용하지는 않게 됩니다.(많은 경우, 사용되지 않는 경우가 발생합니다.) 이런 상황에서 잘못된 요청이 들어와도 사용되지 않는 PathVariable을 위한 검증을 별도로 진행해야 합니다.
하지만, 공통적으로 이야기 된 부분은, 회원가입을 제외한 우리의 모든 서비스는 Lab의 소속이 인증이 되었을 떄, 진행해야 한다는 것이였습니다. 이를 해결하기 위해서, labs/{labId} 의 정보와 token으로 부터 얻은 Member의 labId를 비교하는 인터셉터를 만들어 진행하게 되면, 로직에만 집중된 작업을 할 수 있을 것이라 생각하였고 위의 결정을 내렸습니다.

## query param의 사용
gpuServer에 따른 job 조회의 경우 query_param으로 조회를 진행하게 되고, 가능하면 status에 따른 조회 기능도 query_param으로구현되면 좋겠다는 의견이 나왔습니다.

## 개별 Member jobs 조회
/api/labs/{labId}/jobs/me
의 방식을 선택하였습니다.
조회 후 각 조회를 /api/labs/{labId}/jobs/{jobId} 의 방식을 사용하고 싶었고, members/me에서 차용했습니다.
결정된 api는 아래 문서에서 확인할 수 있습니다. 문서화 작업을 해준 @배럴 감사합니다!

[확정된 api 문서](https://docs.google.com/spreadsheets/d/12JlH36Oltc_EOo3woEob-Pz6llY2SkQ9vsrL1TsdMPg/edit#gid=450048137)
