### ISSUE TITLE
gpuServer 조회 시 Job 상세 정보가 노출되고 있다.

### ISSUE THREAD

**Issue by ecsimsw** [woowacourse-teams/2021-gpu-is-mine#164]
지금 gpuServer를 조회하면 job이 모두 노출된다.
이러면 Job 조회의 권한 확인이 모두 의미가 없다.
외부 사용자가 그냥 serverId만 확인하면 되기 때문이다.

이 부분 작업이 필요한데, 프론트엔드 분들에게 미리 알려야 할 것 같아서
대화하고 작업 진행한다.

![image](https://user-images.githubusercontent.com/46060746/126911326-777589a3-2a02-42f6-befd-29e136388a1e.png)

**Comment by ecsimsw** [comment]
{
    "gpuServers": [
        {
            "id": 1,
            "serverName": "server1",
            "memorySize": 1024,
            "diskSize": 1024,
            "isOn": true,
            "gpuBoard": {
                "id": 1,
                "modelName": "NVIDIA42",
                "performance": 600,
                "isWorking": true
            },
            "runningJob": {
                    "id": 1,
                    "name": "job1",
                    "status": "Running"
                },
            "waitingJobCount" : 2 ,
            "expectedTime" : 소수점까지 생각하겠습니다.
         }   
}

**Comment by 2SOOY** [comment]
// JOB 상세 조회
{
  "gpuServerId": 0,
  "gpuServerName": "string",
  "id": 0,
  "memberId": 0,
  "memberName": "string",
  "name": "string",
  "status": "WAITING",
  "시작시간": "string",
  "dockerHubUrl": "string",
  "소요시간": number,
}

// JOB 로그 데이터
{
  "log": "string"
}

**Comment by ecsimsw** [comment]
## 작업 전 메인페이지 gpus 응답 
{"gpuServers":[{"id":1,"serverName":"test_server_1","memorySize":24,"diskSize":234,"isOn":true,"gpuBoard":{"id":1,"modelName":"adsf","performance":234,"isWorking":false},"jobs":[{"id":1,"name":"MNIST_DEFAULT","status":"RUNNING","memberId":1,"memberName":"name","gpuServerId":1,"gpuServerName":"test_server_1","metaData":"1","expectedTime":"1","calculatedTime":{"createdTime":null,"startedTime":null,"expectedStartedTime":null,"completedTime":null,"expectedCompletedTime":null}},{"id":2,"name":"test1","status":"CANCELED","memberId":9,"memberName":"dd","gpuServerId":1,"gpuServerName":"test_server_1","metaData":"/abc","expectedTime":"234","calculatedTime":{"createdTime":null,"startedTime":null,"expectedStartedTime":null,"completedTime":null,"expectedCompletedTime":null}},{"id":3,"name":"NLP를 사용한 회의 요약 학습","status":"WAITING","memberId":1,"memberName":"name","gpuServerId":1,"gpuServerName":"test_server_1","metaData":"hello","expectedTime":"15","calculatedTime":{"createdTime":null,"startedTime":null,"expectedStartedTime":null,"completedTime":null,"expectedCompletedTime":null}},{"id":4,"name":"학습테스트_1","status":"WAITING","memberId":1,"memberName":"name","gpuServerId":1,"gpuServerName":"test_server_1","metaData":"/test","expectedTime":"12","calculatedTime":{"createdTime":null,"startedTime":null,"expectedStartedTime":null,"completedTime":null,"expectedCompletedTime":null}}]}]}

<br>


![image](https://user-images.githubusercontent.com/46060746/131928907-a10bdc0a-e46b-47e8-8cc4-08b714a7c7ed.png)
