### ISSUE TITLE
3차 데모데이 구현할 기능들을 나열한다

### ISSUE THREAD

**Issue by 2SOOY** [woowacourse-teams/2021-gpu-is-mine#165]
### 회원가입
- [x] 회원가입 폼 컴포넌트 구현
- [x] 회원가입 페이지 구현
    - [x] 관리자로 회원가입 or 연구원으로 회원가입
- [x] 회원 가입 폼 유효성 검사
- [x] 회원가입 비동기 처리중 로딩상태 표시
- [x] useAuth 로 refactoring

### 로그인
- [x] 로그인 폼 컴포넌트 구현
- [x] 로그인 페이지 구현
- [x] 로그인 폼 유효성 검사
- [x] 로그인 정보 저장 관련 정책 결정하기
   - [x] accessToken 을 sessionStorage에 저장
   - [x] accessToken을 axios request header에 항상 실어보내기
   - [x] context api로 추상화(authProvider)
- [x] 로그아웃 기능 구현(일단 accessToken 날리기)
- [x] accessToken 있는 경우 자동로그인 
- [x] accessToken이 있는 경우 member/me 에서 labName 등 정보 fetch 해오기
- [x] 로그인 비동기 처리중 로딩상태 표시

### Job 등록
- [x] Job 등록 페이지 구현

### Job 전체 조회
- [x] Gpu 서버 조회와 유사하게
- [x] status 별 컬럼명 변경 등

### Job 상세 조회
- [x] Job 상세 조회

### GPU 서버 전체 조회
- [ ] GPU 서버 삭제 후 refresh 실행해도 다시 fetch 하지 않음
  - caching 전략의 문제. cache key를 수동으로 입력할 것인가?

### GPU 서버 상세 조회
- [ ] Job 리스트를 테이블 뷰로 보여주기

### 나의 예약 Job 조회
- [ ] 나의 예약 Job 조회

### 공통
- [ ] Form Validation 
  - [ ]  onBlur ? onCHange?
  - [ ] Submit 할 때 validation 이 돌던가, 이미 완벽하게 완료된 validation 값에 접근할 수 있어야 함
- [ ]  API call:  Response status 401 이면 logout 수행
- [x] PublicRoute 구현
- [x] 스웨거에 맞춰서 API 변경
- [ ] API call시 하드 코딩 된 부분 useAuth 사용하여 변경 `labId` 지정하기

**Comment by bigsaigon333** [comment]
3차 데모데이 이후 해결해야할 과제

- [ ] useFetch caching 전략 수정
   - unique 한 cache key 를 지정해주는 방식으로 해야할 듯

- [ ] 전체 조회 리스트를 테이블 뷰로 보여주기

- [ ] 나의 예약 Job 조회 기능 구현

- [ ] Form Validation 안정화 작업(테스트 등)

- [ ] 새로고침 했을때 현재 url으로 접속되게 하기

- [ ] useAuth 고도화

- [ ] 학습중인 Job 로그 자동으로 갱신하게 하기

- [ ] 학습중인 Job 로그 파싱하여 시각화하기
