### ISSUE TITLE
삭제 처리 확인이 필요하다.

### ISSUE THREAD

**Issue by ecsimsw** [woowacourse-teams/2021-gpu-is-mine#166]
당장 생각나는 목록은

- lab이 삭제되면, server, board, job, member 정보가 삭제되는지
- server가 삭제되면 board, job 정보가 삭제되는지
- server가 삭제되면 소프트 삭제를 진행하는지
- member가 삭제되면 본인의 Job 목록은 삭제되는지

**Comment by sjpark-dev** [comment]
#47 #58
