### ISSUE TITLE
GPU Manager EC2를 생성하고 환경 설정을 한다.

### ISSUE THREAD

**Issue by sjpark-dev** [woowacourse-teams/2021-gpu-is-mine#176]
# 이슈 설명

- GPU Manager를 구동할 EC2를 생성한다.
- EC2 서버의 간단한 보안 설정을 한다.
    - 환경변수 적용하기
    - shell prompt 변경하기
- Python 설치

**Comment by sjpark-dev** [comment]
@MyaGya 파이썬 버전은 어떤걸 선호하시나요?

**Comment by MyaGya** [comment]
3.7 선호합니다

**Comment by sjpark-dev** [comment]
Ubuntu 18.04는 파이썬 3.6을 권장합니다.
3.6을 사용하면 docker와 같은 module을 사용하는데 제약이 있을까요?
