### ISSUE TITLE
dev, prod 에서 사용할 DB 연결작업을 진행한다.

### ISSUE THREAD

**Issue by knae11** [woowacourse-teams/2021-gpu-is-mine#188]
# 이슈 설명

- dev, prod 에서 사용할 DB 연결작업을 진행
- EC2에서 DB를 관리하는 방법에 대해서도 공부해볼게요 (의견있다면 댓글로 남겨주시면 공부하는데 참고할게요 :) )
- h2가 아닌 mariaDB를 사용시 사용할 수 있도록 연결해보는 작업을 진행

**Comment by ecsimsw** [comment]
오옷 좋습니다.
인프라도, 도메인도, 여러 사람이 돌아가면서 두루 두루 일 할당이 되었으면 했는데,
배럴이 용기내어주셔서 좋아요.
