### ISSUE TITLE
Flyway 도입을 대화한다. 

### ISSUE THREAD

**Issue by ecsimsw** [woowacourse-teams/2021-gpu-is-mine#189]
음.. 저 이거 테코톡까지 했는데 도입 대화해보면 안될까요..?

열심히 준비했는데, 안된다면 그 의견도 한번 들어보고 싶습니다. 🥲

아 물론 이번 데모 지나고, 어느정도 자리 잡은 후 입니다.

**Comment by bigsaigon333** [comment]
@ecsimsw  도입을 하기로 했으니 이 이슈는 close해도 될까요?

**Comment by MyaGya** [comment]
새 이슈를 파서 PR을 보낼때 해당 이슈까지 함께 종료하도록 할게요
