### ISSUE TITLE
설정 파일을 서브모듈로 옮긴다.

### ISSUE THREAD

**Issue by sjpark-dev** [woowacourse-teams/2021-gpu-is-mine#197]
# 이슈 설명

- properties 설정파일에는 토큰 비밀키, DB 비밀번호 등 중요한 정보가 있습니다.
- 이를 private repository로 옮기고 메인 프로젝트의 서브모듈로 가져오는 것이 좋습니다.

**Comment by wannte** [comment]
![Screenshot from 2021-07-29 21-05-18](https://user-images.githubusercontent.com/49307266/127488832-0e14f07f-110c-4865-ac87-70a41f032249.png)

**Comment by wannte** [comment]
![Screenshot from 2021-07-29 21-19-03](https://user-images.githubusercontent.com/49307266/127490706-2ec8862d-e407-462e-a4c9-699713ac994f.png)
