### ISSUE TITLE
Lab 인증 후, GpuServer가 해당 Lab에 포함되지 않아도 조회 가능 문제를 수정한다.

### ISSUE THREAD

**Issue by ecsimsw** [woowacourse-teams/2021-gpu-is-mine#200]
사용자 토큰으로 labId를 비교하여 lab 권한을 찾기는 하나,
조회를 원하는 server가 실제로 해당 lab에 속하는지에 대한 검증이 없습니다.

A가 lab1에 속해있고, ServerB가 lab2에 속한 상황에서
A의 토큰으로 /api/labs/1/gpus/2 와 같은 요청으로 다른 랩의 서버를 조회할 수 있는 상황입니다.

**Comment by ecsimsw** [comment]
![image](https://user-images.githubusercontent.com/46060746/127541988-c820c124-fabd-4b82-b174-2924241eb2c3.png)

**Comment by ecsimsw** [comment]
제가 생각한 해결 방법은 세가지 입니다.

1. gpus 인터셉터를 만들어 member가 server에 권한을 갖는지 확인한다.

2. 모든 핸들러에 pathVariable labId와 serverId가 유효한지 확인한다.
``` java
@GetMapping("/{gpuServerId}")
public ResponseEntity<GpuServerResponse> findById(@PathVariable Long labId, @PathVariable Long gpuServerId) {
    gpuServerService.validateServerOnLab(gpuServerId, labId);
    GpuServerResponse gpuServerResponse = gpuServerService.findById(gpuServerId);
    return ResponseEntity.ok(gpuServerResponse);
}
```

3. GpuServerService 안에 labId를 같이 받는다.
``` java
@GetMapping("/{gpuServerId}")
public ResponseEntity<GpuServerResponse> findById(@PathVariable Long labId, @PathVariable Long gpuServerId) {
    GpuServerResponse gpuServerResponse = gpuServerService.findById(labId, gpuServerId);
    return ResponseEntity.ok(gpuServerResponse);
}
```

**Comment by knae11** [comment]
혹시 로그인인터셉터부분 config에서 해제하고해도 안 된다는거죠..??
