### ISSUE TITLE
코드 내의 개행 문자에 대한 정책을 설정한다

### ISSUE THREAD

**Issue by MyaGya** [woowacourse-teams/2021-gpu-is-mine#211]
# 이슈 설명

- 개행문자는 윈도우에서 쓰는 CRLF, 맥과 리눅스에서 쓰는 LF 로 두 가지 개행문자가 혼용되어 사용하고 있다
- 이 개행문자를 하나로 통일해야 할지, 유지해야 할지, 이에 따른 소요 사항을 고려하여 정책을 설정할 필요가 있다
#210

**Comment by sjpark-dev** [comment]
이미 레포는 LF로 통일된 상태라서 마갸와 저만
git config --global core.autocrlf true 설정이 되어 있는지 확인하면 될 것 같아요.
