### ISSUE TITLE
그래프 시각화를 위한 라이브러리를 선정한다

### ISSUE THREAD

**Issue by bigsaigon333** [woowacourse-teams/2021-gpu-is-mine#259]
Job 상세조회에서 사용할 그래프 시각화를 위하여 라이브러리를 선정할 필요가 있습니다.

각 라이브러리의 장단점을 비교해서, 어떤 라이브러리를 선정할지 논의가 필요합니다.

제가 생각하는 라이브러리 선정시 주된 고려요소는 다음과 같습니다.

1. 단순히 손쉽게 그래프를 그리는 것이 중요하지 않다고 생각합니다. 
로이드가 공유해준 학습 로드맵상의 그래픽스와의 연계점이 충분히 있었으면 좋겠습니다.
즉, 너무 내부가 블랙박스이면 오히려 저희가 배울 점이 없어서 라이브러리 도입이 아무 의미가 없다고 생각합니다.

2. 러닝커브가 너무 높지도 너무 낮지도 않다. 
1번과 연계되는 내용입니다. 러닝커브가 너무 높아서 1~2주 공부해도 아무것도 시각화 할 수 없다면 적당하지 않겠습니다.
개인적으로 다음주까지 반드시 시각화를 해야한다고는 생각하지 않습니다. 레벨 3 방학도 있고, 레벨 4 기간도 있습니다.
적어도 레벨 4 기간 내에는 원하는 수준의 시각화를 이루어낼 정도의 러닝커브면 저는 수용가능하다고 생각합니다. 

3. 충분히 성숙한 라이브러리이다. 
레퍼런스가 충분히 많으면 좋겠고, 적어도 1.0.0 이상이었으면 좋겠습니다. 0.x 는 기술이 갑자기 변경될 가능성이 높기 때문에, 
가능하면 회피했으면 좋겠습니다.

생각나는건 이정도이고.. 각자 좀 찾아봐서 댓글로 라이브러리 장단점 비교해서 며칠내로 정했으면 좋겠네요 :+1:

**Comment by bigsaigon333** [comment]
한소장님이 말씀해주신 라이브러리
1. ApexChart.js
2. d3.js

**Comment by bigsaigon333** [comment]
### chart.js

쉽고 간단하고, 무엇보다 홈페이지가 예쁘네요 ㅎㅎ

https://www.chartjs.org/docs/latest/charts/line.html

**Comment by 2SOOY** [comment]
> ### chart.js
> 쉽고 간단하고, 무엇보다 홈페이지가 예쁘네요 ㅎㅎ
> 
> https://www.chartjs.org/docs/latest/charts/line.html
