### ISSUE TITLE
GPU 등록, 조회, 삭제 API 를 구현한다

### ISSUE THREAD

**Issue by MyaGya** [woowacourse-teams/2021-gpu-is-mine#30]
# GPU 관련 기능
- GPU 등록
- GPU 조회
- GPU 삭제

**Comment by MyaGya** [comment]
[참고 위키](https://github.com/woowacourse-teams/2021-gpu-is-mine/wiki/%5B2%EC%A3%BC%EC%B0%A8-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B4%80%EB%A0%A8-%ED%9A%8C%EC%9D%98%5D) 
# 이슈 사항 정리
* DB 구조에 따라 조회 기능에서 lab Id가 필요한가?
* put - delete에서의 응답 구조는? - 현재는 203
* GPU 서버의 status 가 얼마나 되는가? enum으로 관리할 것인가?
* 상세조회에서 "가용메모리" "메모리 사용률" 의 의미가 중복된다. "전체 메모리", "사용 메모리" 로 변경 요청
* JOB 관련 구조 변경 요청

= [전체 JOB]
===[실행중인 JOB]
=====[Job 이름]
=====[Job 예상시간(사용자가 최초 등록시 입력)]
=====[기타 서버에서 받아올 데이터 추가될 예정]
===[대기중인 JOB]
=====[Job 이름]
=====[Job 예상시간(사용자가 최초 등록시 입력)]

추가로 이 과정에서 "모든 Jobs 가 끝나는 예상 가용시간" 을 백엔드에서 계산할 것인가 프론트에서 계산할 것인가?

* time 값들 처리 방법

**Comment by MyaGya** [comment]
기본 기능 테스트 레퍼런스 
======
배럴
GPU 기본 CRUD API 관련 Acceptance 5개
======
에드
findGpuSever:
1. lab id가 없는 경우
2. gpu id가 없는 경우
3. find 확인
findAllGpuServer
1. findAll 확인
updateGpuServer
1. gpuServerId가 없는 경우
2. 이름 변경 기능 확인
=====
마갸
delete
1. gpuId가 없는 경우
2. 해당 gpuId가 이미 논리 삭제가 되어있는 경우
3. delete 확인
saveGpuServer
1. gpuServerRequest 없는 경우
2. labId가 없는 경우
3. 저장된 객체 확인
4. 저장 확인
=====
추가 및 개선사항:
transacetion 테스트

**Comment by sjpark-dev** [comment]
GpuService 클래스명을 GpuServerService로 변경했습니다.

**Comment by sjpark-dev** [comment]
gpu로 명명된 패키지, 클래스, 파라미터를 명확히 gpuServer 또는 gpuBoard로 구분하는게 좋을 것 같아요

**Comment by MyaGya** [comment]
저장하는 과정에서 내부 인자에 관한 세세한 테스트는 빼놓았습니다.
이 부분에 테스트를 추가하면 DB 구조가 변경되었을 때 더 빠르게 대응 할 수 있을까요?
아니면 어차피 에러가 뜨는 부분이니까 테스트 코드를 만들지 말까요?
DB 변경에 따른 각 service 의 기능마다 매칭되어 있는 내부 인자를 바꿔주려면 낭비가 심할 것 같습니다 <- 논의 필요

**Comment by sjpark-dev** [comment]
테스트코드 작성하면서 학습한 내용을 공유합니다.
[LazyInitializationException 처리하기](https://github.com/woowacourse-teams/2021-gpu-is-mine/wiki/LazyInitializationException-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0)

**Comment by knae11** [comment]
> 테스트코드 작성하면서 학습한 내용을 공유합니다.
> [LazyInitializationException 처리하기](https://github.com/woowacourse-teams/2021-gpu-is-mine/wiki/LazyInitializationException-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0)

@sjpark-dev 
해당 글에서 JPA 가 기본으로 LAZY를 설정하고 있는건 아니라고 알고 있는데, 혹시 제가 아는 내용이 잘 못 된 것일수도 있어요. 한번 확인해 주시면 좋을 것 같아요! :)

@ManyToOne, @OneToOne: 기본이 즉시로딩
@OneToMany, @ManyToMany: 기본이 지연로딩

로 알고 있네요 :-)

**Comment by sjpark-dev** [comment]
> > 테스트코드 작성하면서 학습한 내용을 공유합니다.
> > [LazyInitializationException 처리하기](https://github.com/woowacourse-teams/2021-gpu-is-mine/wiki/LazyInitializationException-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0)
> 
> @sjpark-dev
> 해당 글에서 JPA 가 기본으로 LAZY를 설정하고 있는건 아니라고 알고 있는데, 혹시 제가 아는 내용이 잘 못 된 것일수도 있어요. 한번 확인해 주시면 좋을 것 같아요! :)
> 
> `@ManyToOne, @OneToOne`: 기본이 즉시로딩
> `@OneToMany, @ManyToMany`: 기본이 지연로딩
> 
> 로 알고 있네요 :-)

내부 코드 확인 결과 배럴 말이 맞네요!
말씀하신대로 어노테이션에 따라 FetchType이 다르네요!

글 수정하겠습니다! 감사합니다! 👍

**Comment by sjpark-dev** [comment]
[관련 PR](https://github.com/woowacourse-teams/2021-gpu-is-mine/pull/57)이 머지되었으니 close 합니다.
