### ISSUE TITLE
GPU 페이지에 대한 Http 요청, 응답 프로퍼티명을 구체화한다.

### ISSUE THREAD

**Issue by ecsimsw** [woowacourse-teams/2021-gpu-is-mine#33]

**Comment by knae11** [comment]
[API 회의 내용 - 위키](https://github.com/woowacourse-teams/2021-gpu-is-mine/wiki/%5B2%EC%A3%BC%EC%B0%A8-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B4%80%EB%A0%A8-%ED%9A%8C%EC%9D%98%5D)
