### ISSUE TITLE
Github 정책 변경으로 인한 jenkins 설정 필요

### ISSUE THREAD

**Issue by wannte** [woowacourse-teams/2021-gpu-is-mine#332]
# 이슈 설명

- 이슈에 대한 설명을 해주세요.
8월 13일자로 id, password로 github 접근방식이 수정이 되어 내부 사용하는 credential 변경 필요
https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/
- 라벨을 달아주세요.

**Comment by sjpark-dev** [comment]
https://newbedev.com/how-to-use-github-personal-access-token-in-jenkins
참고 바랍니다.
