### ISSUE TITLE
1.0.0 배포를 진행한다

### ISSUE THREAD

**Issue by MyaGya** [woowacourse-teams/2021-gpu-is-mine#340]
# 이슈 설명

- 이슈에 대한 설명을 해주세요.
- 라벨을 달아주세요.

**Comment by knae11** [comment]
http 설정 프론트에서 https 로 리다이렉트하게 한다.

**Comment by MyaGya** [comment]
#338 
#337 
#336 
#334

**Comment by MyaGya** [comment]
2021/08/17 작업 완료

# 처리사항

- www.gpuismine.com / gpuismine.com CORS 설정 추가
- DataLoader main 에 추가

# 추가 이슈

- http 설정 프론트에서 https 로 리다이렉트하게 한다.
- admin 관련 설정(CORS, DataLoader, 관리자 계정 추가 기능 등)
