### ISSUE TITLE
최초 로그인시 myInfo를 불러오지 못한다.

### ISSUE THREAD

**Issue by 2SOOY** [woowacourse-teams/2021-gpu-is-mine#353]
![image](https://user-images.githubusercontent.com/46412689/131947656-ab1ea192-507a-4b95-850d-5e970b8dac3e.png)

+ 토큰을 저장하는 순서가 myInfo 불러오기 이전에 수행되어야함

**Comment by bigsaigon333** [comment]
### 버그 현황 추가
1. 관리자로 로그인 한 후 로그아웃하고, 일반 사용자로 로그인하면 관리자 뷰가 보인다 -> 새로고침하면 일반 사용자 뷰가 보인다
2. 일반 사용자로 로그인 한 후 로그아웃하고, 관리자로 로그인하면 일반 사용자 뷰가 보인다-> 새로고침하면 관리자 뷰가 보인다
