### ISSUE TITLE
테스트 클래스 간의 데이터 침범 오류를 수정한다.

### ISSUE THREAD

**Issue by MyaGya** [woowacourse-teams/2021-gpu-is-mine#369]
**버그 설명**
테스트 패키지가 서로를 침범하고 있어 전체 테스트를 돌릴 경우 테스트가 실패하지만 실패한 패키지만을 테스트 할 경우 테스트가 성공한다

**재현 방법**
`WorkerServiceTest`  의 해당 부분에서 이메일을 기존에 존재하는 `email@email.com` 으로 변경한다
![image](https://user-images.githubusercontent.com/38939015/132332534-cae8834d-4f96-4880-b1e6-f347a36c46c2.png)

**예상 응답**
테스트 통과

**스크린샷**
## 전체 테스트에서 에러 발생
![image](https://user-images.githubusercontent.com/38939015/132332653-1c6039e2-3802-49bb-8913-264f1644295b.png)

## 해당 패키지만 테스트 할 경우 에러 미발생
![image](https://user-images.githubusercontent.com/38939015/132332715-f8846d75-fd10-44ac-a2d9-7e28126cf37c.png)

## 웹 환경에서는 테스트 모두 통과
![image](https://user-images.githubusercontent.com/38939015/132332739-0ffdf86d-6b7c-463f-9d2d-f61c8e8aea30.png)

## 일부 PC에서는 다른 테스트 패키지에서 에러 발생
![image](https://user-images.githubusercontent.com/38939015/132332785-58d797eb-7f32-48eb-8727-370f1e6f7e33.png)

**Comment by sjpark-dev** [comment]
원인 파악
- encrypt와 mail 테스트가 local profile로 돌아감
- local profile의 dataloader가 동작해서 DB에 데이터를 저장
- 다른 테스트에서 데이터를 저장할 때 중복 유효성 검사에서 걸림

해결 방법
- encrypt와 mail 테스트를 test profile로 바꿔서 dataloader의 동작 방지

재발 방지 대책
- 앞으로 스프링의 컨택스트를 사용하는 테스트는 test profile을 적용
