### ISSUE TITLE
사용하지 않는 패키지를 제거한다

### ISSUE THREAD

**Issue by bigsaigon333** [woowacourse-teams/2021-gpu-is-mine#370]
사용하지 않는 패키지가 많이 있습니다. 

~`@babel/core`,~ `babel-loader`, `compression-webpack-plugin`, `cross-env` 를 삭제합니다.

`@babel/core`는 스토리북 빌드시 필요하네요..

**Comment by 2SOOY** [comment]
cross-env 사용 X => 웹팩에서 환경 변수 처리할 수 있도록 주입
