### ISSUE TITLE
로그 관리 상태에 대해 점검한다.

### ISSUE THREAD

**Issue by knae11** [woowacourse-teams/2021-gpu-is-mine#376]
# 이슈 설명

- 프로젝트 로그 사항에 대해 개선할 방향이 있는지 점검해본다.

**Comment by wannte** [comment]
로그 파일 구조 개선.

당일 파일
logs/ 디렉토리 밑에 파일로 존재
access.log, debug.log, info.log, warn.log, error.log 가 존재 하도록. (같은 디렉토리 안에 있을 때, 더 효율적인 작업이 가능하다고 판단)

이전 파일
logs/backup/{yyyy-MM-dd}/ 디렉토리 밑에 
access-{yyyy-MM-dd}_%i.log 의 형태로 위의 로그들 존재. (위와 같은 이유로 일별로 로그가 관리되는 것이 좋다고 판단. 파일 명에 일자를 제외할까도 고민했으나, 일자를 명시해주는 게 더 좋다고 판단.

**Comment by wannte** [comment]
flywaydb debug 로그에 경우, dev 브랜치에서는 debug레벨로 로깅을 할 수 있기 때문에, 우선 별도로 지정하지는 않게 수정
(로깅 전략을 로깅 레벨별로 구분하고 있기 때문에, main서버에서는 Flyway의 마이그레이션 과정을 로깅으로 남길 필요까지는 없다고 판단)

Filter- Match MisMatch (http://logback.qos.ch/manual/filters.html)
Accept는 early return의 개념으로 받아드리면 좋을듯!

**Comment by wannte** [comment]
dev서버에 직접 연결하고, 클라우드 와치에 붙여볼 예정
