### ISSUE TITLE
ElasticSearch의 OOM 에러의 원인을 분석하고 해결한다.

### ISSUE THREAD

**Issue by wannte** [woowacourse-teams/2021-gpu-is-mine#381]
# 이슈 설명
ElasticSearch가 어느정도 시간이 지나간 이후에 죽는 현상이 있음.
- 이슈에 대한 설명을 해주세요.
- 라벨을 달아주세요.

**Comment by wannte** [comment]
Manage your data -> Monitor the stack 에서 elasticsearch의 현재 상태를 확인해볼수 있음
![Screenshot from 2021-09-09 17-13-25](https://user-images.githubusercontent.com/49307266/132649025-5a97c4ff-6747-45a7-ad46-666e076d5ca3.png)

JVM 이 아무런 작업이 없을 때도, 80% 의 heap memory를 차지하고 있음.

**Comment by knae11** [comment]
# 문제원인
- 설정된 heap memory 가 작았다.
### 기존
- `ES_JAVA_OPTS: "-Xmx256m -Xms256m"`
- `LS_JAVA_OPTS: "-Xmx256m -Xms256m"`
- elasticsearch, logstash 의 heap 메모리 사이즈가 256m 으로 설정되어 있었음

### 변경
- `ES_JAVA_OPTS: "-Xmx1g -Xms1g"`
- `LS_JAVA_OPTS: "-Xmx1g -Xms1g"`
- elasticsearch, logstash 의 heap 메모리 사이즈를 1g로 늘림
