### ISSUE TITLE
프로젝트 마크업 구조를 개선한다.

### ISSUE THREAD

**Issue by 2SOOY** [woowacourse-teams/2021-gpu-is-mine#393]
2021년 10월 5일 화요일 10:00까지

1. h1 태그 이외의 나머지 h태그들(h2, h3, ...) 등을 잘 활용하여 문서의 구조를 명확하게 하기
2. 현재 div로 작성된 footer 태그 footer로 변경
3. 로고 태그 구조 변경 (현재 a > div ) 구조로 이뤄짐
4. 반응형 디자인 대응하기

**Comment by bigsaigon333** [comment]
5. favicon.ico 를 추가한다
