### ISSUE TITLE
DB 도커 -> EC2로 마이그레이션

### ISSUE THREAD

**Issue by wannte** [woowacourse-teams/2021-gpu-is-mine#398]
# 이슈 설명

- 이슈에 대한 설명을 해주세요.
- 라벨을 달아주세요.

**Comment by wannte** [comment]
db안에 값을 유지하면서 진행해보는 경험도 해보면 좋을 듯 합니다.

**Comment by knae11** [comment]
# DB docker -> EC2 로 전환

1. DB 덤프
- docker에 접속하여 DB 컨테이너에 접속 `docker exec -it [container id] /bin/bash` 
- `mysqldump -u [계정] -p [db이름] > [백업 파일 이름].sql`
- docker 에 있는 덤프파일을 docker 밖으로 복사 `docker cp [containerId]:[백업 파일 이름].sql [원하는 파일 위치]`

2.

**Comment by sjpark-dev** [comment]
MariaDB에 원격 접속 허용하는 방법
https://mariadb.com/kb/en/configuring-mariadb-for-remote-client-access/#finding-the-defaults-file
