### ISSUE TITLE
Branch 전략을 대화한다.

### ISSUE THREAD

**Issue by ecsimsw** [woowacourse-teams/2021-gpu-is-mine#4]
- develop / dev-front / dev-back / test / docs

**Comment by sjpark-dev** [comment]
07.06 화요일 Git 브랜치 강의를 듣고 정하는게 좋을 것 같습니다.

**Comment by bigsaigon333** [comment]
각 브랜치 별 추천되는 merge 전략이 있네욤 
참고차 공유합니다!

https://meetup.toast.com/posts/122

**Comment by bigsaigon333** [comment]
![image](https://user-images.githubusercontent.com/31029000/124546252-51c72180-de65-11eb-9578-069f371b880e.png)

**Comment by bigsaigon333** [comment]
https://techblog.woowahan.com/2553/

**Comment by bigsaigon333** [comment]
main
develop
feature/*

**Comment by 2SOOY** [comment]
`feature` -> `develop` -> `main` flow로 merge를 진행함

+ `feature`에서 `develop`으로 날린 PR이 approve될 경우 `squash merge`한다
