### ISSUE TITLE
API 서버의 DNS 설정을 가비아로 이전한다.

### ISSUE THREAD

**Issue by sjpark-dev** [woowacourse-teams/2021-gpu-is-mine#412]
API 서버를 등록했던 무료 도메인의 만료기간이 얼마 남지 않았다.
가비아의 도메인을 사용하도록 바꿔야한다.
그 후 프론트엔드 코드의 API 도메인 주소도 바꿔야 한다.
![image](https://user-images.githubusercontent.com/66653739/135856819-eaeaabd5-0bda-4dd4-97b3-6aabcee94024.png)

**Comment by wannte** [comment]
어떤 uri 주소로 바꾸는 게 좋을까요?

main 서버
cloudfront 주소 : www.gpuismine.com
api 주소 : api.gpuismine.com

---

dev 서버
cloudfront 주소 : dev.gpuismine.com
api 주소 : ???.gpuismine.com


생각나는 주소를 자유롭게 남겨주세요! 좋다고 생각하는 의견을 언급해줘도 좋구요!

제가 지금 생각나는 부분들은 다음과 같습니다.

dev-api.gpuismine.com
devapi.gpuismine.com

**Comment by sjpark-dev** [comment]
dpi.gpuismine.com 제안 해봅니다.

**Comment by sjpark-dev** [comment]
기존의 무료 도메인을 사용하지 않으면 가비아에도 txt record 추가해야 하지 않나요?

**Comment by wannte** [comment]
let's encrypt를 사용하게 될때, txt record로 검증을 진행해야 될거에요

txt record를 추가한다는 표현이 조금 모호하다고 생각하는데, 일시 비밀번호?를 던져줘서 해당 도메인을 너가 진짜 가지고 있는거야? 를 거증하는 과정이라 생각해요!

**Comment by bigsaigon333** [comment]
`https://dev-api.gpuismine.com` 확정 땅땅땅

**Comment by sjpark-dev** [comment]
도메인 문제 없다고 확인되면 close 하겠습니다!
