### ISSUE TITLE
데모 전 서비스 개선사항에 대해 논의한다.

### ISSUE THREAD

**Issue by knae11** [woowacourse-teams/2021-gpu-is-mine#445]
# 이슈 설명

- main 배포 전 개선사항을 확인한다.

**Comment by 2SOOY** [comment]
+ 매니저, 유저에서 내 정보 및 유저 관리 탭 제거하기
+ Job 요약 정보 및 GPU 서버 요약 정보 카드처럼 background 추가하기
+ 페이지 레이아웃 우측 하단에 ❓ 와 같은 아이콘 넣어서 클릭하면 `페이지 이동` or `모달`로 프로젝트 소개 or 사용법 정도 추가하면 좋을 듯
+ 실행중인 Job이 없을 때 Job 요약 정보 카드 뷰 필요

**Comment by bigsaigon333** [comment]
Toast 위치 선정 #439
