### ISSUE TITLE
서비스 내부에서 사용하는 Docker Hub Url 관련 정보를 통일한다

### ISSUE THREAD

**Issue by MyaGya** [woowacourse-teams/2021-gpu-is-mine#452]
# 이슈 설명

* 현재 docker Hub Url 을 다 다르게 사용하고 있다.

* Docker Hub Url -> Dokcer Hub Image
* Placehold -> 계정명/저장소명:버전
* 추가로 등록시에는 `aprn7950/mnist_test_auto` 를 테스트 해 볼 수 있는 버전으로 알려준다

**Comment by bigsaigon333** [comment]
DockerHub 관련 Form 수정
