### ISSUE TITLE
main 서버 Let's Encrypt 인증서를 재발급 받는다.

### ISSUE THREAD

**Issue by sjpark-dev** [woowacourse-teams/2021-gpu-is-mine#547]
main 서버의 Let's Encrypt 인증서가 오늘 만료 예정입니다.
조치는 #411 와 동일하고 서버만 dev에서 main으로 바뀌었습니다.
추가로 가비아에 DNS Text Records를 등록해야 합니다.

**Comment by wannte** [comment]
It's done!
