### ISSUE TITLE
GitHub token을 재발급하여 Jenkins에 등록한다.

### ISSUE THREAD

**Issue by sjpark-dev** [woowacourse-teams/2021-gpu-is-mine#548]
지금 Jenkins에 사용되는 GitHub token이 만료 되었다.
GitHub에서 token을 재발급하고 Jenkins에 재등록한다.

**Comment by sjpark-dev** [comment]
Jenkins 페이지 -> Jenkins 관리 ->  Manage credentials -> 해당 credential의 password update

**Comment by sjpark-dev** [comment]
정상 동작 확인 완료

**Comment by wannte** [comment]
:+1:
