### ISSUE TITLE
엔티티 연관관계 매핑을 명확히한다.

### ISSUE THREAD

**Issue by sjpark-dev** [woowacourse-teams/2021-gpu-is-mine#59]
연관관계 매핑이 통일되지 않은 상태입니다.

개선 사항
- 연관관계를 하나의 방식으로 통일
- 필요시 편의 메서드 작성

**Comment by knae11** [comment]
나도 초기 엔티티 설계가 나온 입장에서 모두의 의견 및 토론이 필요하다고 생각함

# 안건1
1. 여기까지 일단 두고 GPU 기능에 집중할 것인지
2. 여기서 GPU 이외 관계 도메인 기능 및 연관 설계에 집중할 것인지

**Comment by knae11** [comment]
# 안건2: 연관관계 매핑
- 연관관계에 대한 매핑 문제도 이 시점에서 논의할 필요가 있다고 생각함
- 연관관계 및 객체 관계 그래프를 같이 그려보고 정리하고 넘어가야 한다고 생각함
## 참고자료
1. [일대다 쿼리문에 대해 내가 실험해본  글](https://nauni.tistory.com/273)
2. 단방향으로 간다면 어떤 단방향으로 갈건지
3. 양방향으로 열어줄 것이 있다면 어떤 것을 열어줄 것인지
4. 객체가 아닌 id를 필드로 가지게 할 것인지

### 진짜 소견(참고자료)
- 1번 글을 작성하고 그냥 개별적으로 하는 스터디에서 다른 개발자들에게 의견을 물었음
    - 본인이라면 다대일 단방향으로 설계할 것이란 의견이 많았음
    - 혹은 id를 필드로 가질 것이다라는 의견도 많았음(차라리 연관관계를 맺지 않을 것이다라는 의견도 좀 있었음)
    - 즉, 온전한 객체를 필드로 가져야 겠다는 생각이 적었음(객체지향에 너무 생각하지 말고 데이터 중심적으로 설계하는 듯?!)
    - 양방향 매핑은 지옥철 급행열차라고 모두가 입모아 얘기하더라^_^ (어쩔 수 없이 뚫는 경우가 있다고는 하는데..)

**Comment by ecsimsw** [comment]
제 견해와 근거는 다음과 같습니다.

1. 가급적 단방향 매핑으로 가자.
 - 양방향 매핑으로 할 경우, 관계의 '주'를 고민하며 관계에 대한 로직을(이를 테면 연관 관계 편의 메서드를) 정의해줘야하고, 이 과정에서 실수하기 좋다고 생각합니다.
 - 실수하기 좋은 구실이 되므로, 테스트 코드에 대한 비용이 많아지고, 협업 과정에서 관계 해석에 비용이 생깁니다.
 - 순환참조의 문제를 야기하기 좋습니다.

2. 우리의 로직을 단방향 매핑으로 짤 수 있는가?
 - 저는 문제 없다고 생각합니다. 반대로, 양방향 매핑이 반드시 필요한 상황이 생기는 경우는 객체 설계가 잘못되었다고 생각하고 있습니다.
 
3. 그럼 양방향 매핑 같은게 왜 있는가. 어떤 상황에서 써야 한다고 생각하는가
 - 이미 단방향으로 모든 서비스가 만들어졌는데, 새로운 기능을 개발하는 도중 역방향으로 객체 참조가 필요한 경우가 생겼을 때, 임시 방편으로 역방향 참조를 뚫어두기 좋은 방법이라고 생각합니다. 다만, 장기적으로 봤을 때도 그 관계가 긍정적일까는 잘 모르겠습니다. 그런식으로 양방향 관계가 많아지면 구조가 엉망이 되겠지요.

4. 확장의 의미?, 양방향으로 두면 확장에 유리하다?
 - 이 부분에 대해서 잘 이해가 되지 않았습니다. 
 - GpuServer와 GpuBoard를 1:1 양방향 구조로 둔 이유를 그 관계가 1:N 이 되는 확장이 생겼을 때 유리하다는 의견이 나왔던 것 같은데, 1:1 단방향 구조에서 1:N 단방향 구조로 확장되는 것과 어떤 점이 다른지, 오히려 연관관계 편의 메서드까지 고려하면 오히려 1:1 단방향 -> 1:N 단방향이 더 쉬운게 아닌지 생각하고 있습니다. (특히 현재 코드에서 GpuBoard.getGpuServer()가 없다고 알고 있습니다. 그것을 가정한 생각이었습니다.)

**Comment by knae11** [comment]
저도 다대일 단방향,  혹은 아이디로만 참조하는것도 좋은 생각 같다는 의견변경입니다. ㅎㅎㅎ

**Comment by knae11** [comment]
다만 1:n 단방향이 아닌 n:1 단방향으로 갔으면 하는 마음. 그리고 gpu보드와 job의 관계는 너무나 대놓고 깊은 연관관계라고 생각하기때문에 이부분에서는 양방향을 고려하는것도 나쁘지않다생각합니다.

**Comment by sjpark-dev** [comment]
저도 다대일 단방향 의견에 동의합니다.
양방향 매핑은 정말 필요한 경우에만 하는게 좋을 것 같네요!

**Comment by sjpark-dev** [comment]
이 이슈는 의견이 수렴되었으니 close 하겠습니다.
