### ISSUE TITLE
테스트를 위한 사전 데이터 생성 방법을 고민한다.

### ISSUE THREAD

**Issue by sjpark-dev** [woowacourse-teams/2021-gpu-is-mine#60]
현재 테스트를 위한 사전 데이터를 data.sql에 만들고 사용하고 있습니다.

[완태의 의견](https://github.com/woowacourse-teams/2021-gpu-is-mine/pull/57#discussion_r667278680)을 기반으로 어떻게 개선할 수 있을지 고민할 필요가 있습니다.

**Comment by knae11** [comment]
테스트 방법에 대한 의견이 갈린다면 논의가 필요하다는 것에 동의

**Comment by MyaGya** [comment]
저도 해당 의견에 동의합니다
#30 구현중 논리 삭제 기능을 만들어야 했는데 해당 기본값이
Entity객체를 타고 만들어 졌을 때에만 `false` 값으로 기본 지정이 되었기 때문에 쿼리문으로 직접 만드는 순간 DB상에 null로 적용되었습니다.
따라서 `fixture` 등의 방법을 사용하는 것이 좋아보입니다

**Comment by sjpark-dev** [comment]
지금 생각나는 방법은 2가지입니다.

1. fixture(@BeforeEach)로 데이터 생성
2. Util 클래스를 만들어서 static 메소드로 데이터 생성

**Comment by ecsimsw** [comment]
저도 CRUD가 만들어진 시점에서 data.sql에 의존한 테스트 코드는 지양해야한다고 생각합니다.
