### ISSUE TITLE
응답코드, 예외처리 계층구조에 대해 논의한다.

### ISSUE THREAD

**Issue by knae11** [woowacourse-teams/2021-gpu-is-mine#61]
# 이슈 설명
- 아래 항목에 대한 논의가 필요하다고 생각
    - 각 상황에 따른 응답코드를 어떻게 정의하고 갈 것인지
    - 예외 처리를 어떤 방식으로 할 것인지
    - 예외 처리 계층구조는 어떻게 잡을 것인지

**Comment by MyaGya** [comment]
#12 
백엔드끼리 해당 이슈랑 묶어서 이야기해보죠
