### ISSUE TITLE
패키지 구조를 재정의한다.

### ISSUE THREAD

**Issue by ecsimsw** [woowacourse-teams/2021-gpu-is-mine#62]
![image](https://user-images.githubusercontent.com/46060746/125168849-5cc1df00-e1e2-11eb-97e2-9588deef3ca5.png)

도메인 우선으로 패키지 구조를 가져가기로 했으나, gpuServer 패키지를 너무 크게 잡아, 사실상 레이어 우선 순위와 다를바 없는 패키지 구조가 되었습니다.

재정의 할 필요가 있을 것 같습니다.

모든 BE 팀원이 투표를 할지, 한 두명이 선 작업하고 피드백을 주는 방식으로 진행할지 의견을 듣고 싶습니다.

**Comment by wannte** [comment]
dto의 배치를 어떻게 진행할지도 결정해야 할 것 같아요

각각의 도메인별로 있을지, 아니면 전체로 관리할지요.

EmptyJsonResponse ExceptionResponse와 같은 클래스의 경우에는 어디서 관리할지도요!

**Comment by ecsimsw** [comment]
코기 제안

![image](https://user-images.githubusercontent.com/46060746/127557217-a2873b73-2744-4a58-a94b-09ca2452c34f.png)
