### ISSUE TITLE
엔티티 필드 검증을 한다.

### ISSUE THREAD

**Issue by sjpark-dev** [woowacourse-teams/2021-gpu-is-mine#66]
[코기 의견](https://github.com/woowacourse-teams/2021-gpu-is-mine/pull/57#discussion_r667363662)대로 엔티티의 필드 검증이 필요합니다.

**Comment by ecsimsw** [comment]
이슈 63과 중복!!

**Comment by bigsaigon333** [comment]
#63

**Comment by sjpark-dev** [comment]
#63과 중복이므로 close합니다.
