### ISSUE TITLE
Job API에서 MemberId를 받는 방법을 고민한다.

### ISSUE THREAD

**Issue by sjpark-dev** [woowacourse-teams/2021-gpu-is-mine#71]
현재는 LabUserId를 query string으로 받고 있습니다.

나중에 JobRequest 또는 URL path에 포함시킬 수 있을 것 같습니다.

**Comment by ecsimsw** [comment]
로그인 기능이 포함되면 로그인 유저 정보를 어떻게 받을지 고민!

**Comment by wannte** [comment]
token 쓸래

**Comment by sjpark-dev** [comment]
저는 인터셉터 쓰고 싶어요!

**Comment by knae11** [comment]
OAuth 고려는 없을까요?ㅎㅎ

**Comment by ecsimsw** [comment]
Close 요청입니다!
