### ISSUE TITLE
린트 설정을 고려해본다.

### ISSUE THREAD

**Issue by knae11** [woowacourse-teams/2021-gpu-is-mine#79]
# 이슈 설명

- 린트 설정하기
- 푸쉬 전에 포맷팅 강제하기

**Comment by wannte** [comment]
사람마다 린트 설정이 달라서 이 부분 통일하는게 좋겠네요

**Comment by bigsaigon333** [comment]
프론트도 같이 합시다 ㅎㅎ 

도구는 아마 다르겠지만..?

**Comment by bigsaigon333** [comment]
어떻게 강제할 생각이에요? git hooks? 아니면 github actions?

**Comment by wannte** [comment]
https://velog.io/@yuriyoon1009/auto-code-formatting

commit 단위로 진행하는 방법도 있는 거 같아요. lint의 경우 commit 단위로 설정해도 좋을 듯 해요.(git hook)

언어마다 적용방식이 달라보이긴 하는데, 좀 더 찾아보겠습니다!
java는 https://gist.github.com/davetron5000/37350 요런 느낌으로 쓰는 것 같긴한데
