### ISSUE TITLE
Job의 인수테스트를 작성한다.

### ISSUE THREAD

**Issue by sjpark-dev** [woowacourse-teams/2021-gpu-is-mine#82]
# 이슈 설명

- 인수테스트를 작성하기 위해서는 DB에 사전 데이터가 필요
- 기존에는 data.sql을 통해 사전 데이터를 DB에 저장
- data.sql을 삭제하면서 실제 요청을 통해 사전 데이터를 DB에 저장해야 함
- 실제 요청에는 각 도메인별 컨트롤러 + 서비스가 필요함
- 하지만 아직 구현되지 않아서 인수테스트를 나중에 해야 함

**Comment by wannte** [comment]
구체적으로 `Job의 인수테트를 작성한다` 정도로 작성하면 더 좋을 것 같네요!

**Comment by sjpark-dev** [comment]
제목 수정했습니다!

**Comment by ecsimsw** [comment]
Close 요청입니다!
