### ISSUE TITLE
issue, commit, PR 작성 컨벤션을 정한다.

### ISSUE THREAD

**Issue by ecsimsw** [woowacourse-teams/2021-gpu-is-mine#9]
- [feat] [issue] [refactor] [docs] [fix] 
- Assignees
- Labels

**Comment by sjpark-dev** [comment]
Github issue, commit, PR, wiki 작성이 익숙하지 않은 사람을 위한 특강을 짧게 가졌으면 합니다.

**Comment by bigsaigon333** [comment]
Github Issues 템플릿 제안
1. 제목은 한글・문장형으로 쓴다.
2. 카테고리화는 Label을 이용한다.

**Comment by bigsaigon333** [comment]
feat: 회원가입, 로그인 페이지 접속시 처음 Input을 포커스한다

fix: 역 관리 reset action 실행시 메세지도 초기화한다


 
feat: Confirm 컴포넌트를 구현하여 window.alert를 대체한다


refactor: 비정상적인 접근에 대한 알림에 Alert컴포넌트를 이용한다


refactor: Alert 컴포넌트를 추상화한다

 
fix: 사용되지 않는 커스텀 훅을 제거한다

refactor: 서버 선택 페이지의 불필요한 api콜을 제거한다

**Comment by ecsimsw** [comment]
feat: 토큰을 이용한 사용자 인증 / 사용자 예외 처리

**Comment by bigsaigon333** [comment]
https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#

**Comment by knae11** [comment]
# 컨벤션

## 이슈

- 이슈 컨벤션
    - 이슈는 라벨링으로 구분
        - 한글로 작성
    - 문장형으로 제목작성
    - PR로 이슈 close

## 위키

- 주간 단위로 파일생성
- 일단위로 내용 반영하여 작성
- 내부에서 일단위로 구분만 잘 되게 하면 됨

## 커밋컨벤션

- 한글로 작성
- Angular Commit Message Convention 따름
- 단언형으로 작성

**Comment by knae11** [comment]
https://gist.github.com/stephenparish/9941e89d80e2bc58a153

**Comment by bigsaigon333** [comment]
## 제안합니다 :hand: 

FE, BE 커밋이 서로 섞이다보니 이를 구분하는 것이 좋을 것 같습니다.

scope 에 항상 be 또는 fe를 명시하는 게 어떨까요?

```
// 예시
chore(fe): 패키지 설치 및 환경설정  
feat(fe:hooks) 마운트 될 때 실행되는 커스텀 훅 구현
```
