### ISSUE TITLE
update 정책에 대해 논의한다.

### ISSUE THREAD

**Issue by knae11** [woowacourse-teams/2021-gpu-is-mine#90]
# 이슈 설명

- Member, Lab, Job, Server 등등 업데이트 정책에 대해 논의한다.

**Comment by ecsimsw** [comment]
Member의 어떤 필드까지 업데이트를 허용할 것인가

<img width="698" alt="image" src="https://user-images.githubusercontent.com/46060746/126598548-2655089f-1ce0-48af-b410-8c6a142ad726.png">

**Comment by wannte** [comment]
MemeberType, Lab 수정 불가

**Comment by wannte** [comment]
Member 만 완태가 가져감
